# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0cbedfd14ec46c440f48514a1ce035c"
name = "dear-recon"
application_url = "https://dear-recon.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  topics = [ "orders/updated", "refunds/create", "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_orders,read_products,read_returns"

[auth]
redirect_urls = [
  "https://dear-recon.onrender.com/auth/callback",
  "https://dear-recon.onrender.com/auth/shopify/callback",
  "https://dear-recon.onrender.com/api/auth/callback"
]
